# Generated by Django 5.2.5 on 2025-08-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signwords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignLanguageSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="세션 ID", max_length=255, unique=True),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, help_text="사용자 ID", max_length=100, null=True
                    ),
                ),
                (
                    "session_name",
                    models.CharField(
                        blank=True, help_text="세션 이름", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="세션 설명", null=True),
                ),
                (
                    "total_frames",
                    models.IntegerField(default=0, help_text="총 프레임 수"),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, help_text="처리된 프레임 수"),
                ),
                (
                    "keypoints_detected_frames",
                    models.IntegerField(
                        default=0, help_text="키포인트가 감지된 프레임 수"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="세션 시작 시간"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="세션 종료 시간", null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(default=0.0, help_text="세션 지속 시간 (초)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="세션 활성 상태"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("processing", "처리중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        help_text="처리 상태",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "수어 세션",
                "verbose_name_plural": "수어 세션들",
                "db_table": "sign_language_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SignLanguageKeypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, help_text="세션 ID", max_length=255
                    ),
                ),
                ("frame_number", models.IntegerField(help_text="프레임 번호")),
                (
                    "vector_id",
                    models.CharField(
                        help_text="Pinecone 벡터 ID", max_length=255, unique=True
                    ),
                ),
                (
                    "keypoints_json",
                    models.TextField(help_text="키포인트 데이터 (JSON)"),
                ),
                (
                    "metadata_json",
                    models.TextField(
                        blank=True, help_text="메타데이터 (JSON)", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 시간"),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, help_text="사용자 ID", max_length=100, null=True
                    ),
                ),
                (
                    "sign_word",
                    models.CharField(
                        blank=True, help_text="수어 단어", max_length=200, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, help_text="신뢰도 점수"),
                ),
                (
                    "pose_detected",
                    models.BooleanField(default=False, help_text="포즈 감지 여부"),
                ),
                (
                    "left_hand_detected",
                    models.BooleanField(default=False, help_text="왼손 감지 여부"),
                ),
                (
                    "right_hand_detected",
                    models.BooleanField(default=False, help_text="오른손 감지 여부"),
                ),
                (
                    "face_detected",
                    models.BooleanField(default=False, help_text="얼굴 감지 여부"),
                ),
            ],
            options={
                "verbose_name": "수어 키포인트",
                "verbose_name_plural": "수어 키포인트들",
                "db_table": "sign_language_keypoints",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "frame_number"],
                        name="sign_langua_session_5a98e5_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="sign_langua_user_id_1f9aa3_idx"
                    ),
                    models.Index(
                        fields=["sign_word"], name="sign_langua_sign_wo_e35da8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="sign_langua_created_b8d802_idx"
                    ),
                ],
            },
        ),
    ]
